added 2

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -1,9 +1,9 @@
 name: Real world PR-gate
 
 on:
-  workflow_dispatch:
-  #pull_request:
-    #branches: [main]
+  #workflow_dispatch:
+  pull_request:
+    branches: [main]
 
 jobs:
 
@@ -36,10 +36,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-     #`feature/*`, `fix/*`, or `docs/*`
       - name: check pattern
         run: |
           branch=${{ github.head_ref }}
-          echo "$branch"
+          pattern="^(feature|fix|docs)\/.*"
+
+          if [[ ! "$branch" =~ "$pattern" ]]; then
+            echo "Invalid branch"
+            exit 1
+          fi
+
+  pr-body-check:
+    runs-on: ubuntu-latest
+
+    steps:
+     
+      - name: Check description
+        run: |
+          echo "${{ github.event.pull_request.body }}"
+
 
               
